#!/usr/bin/env python
import sys;
import json;

data = json.loads(sys.stdin.read())
data = json.dumps(data, indent=2, sort_keys=True)

if len(sys.argv) != 1:
    data = data.replace('"', '\\"')
print(data)
